accounts:
  - awsAccessKey: ""
    awsSecretKey: ""
    displayAccountName: ""
    
    # Regions where elastiCache is registered
    # Allowed values: ap-southeast-1, ap-southeast-2, ap-northeast-1, eu-central-1, 
    #                 us-east-1, eu-west-1, us-west-1, us-west-2, sa-east-1
    #
    regions: ["us-east-1"]
    
credentialsDecryptionConfig:
    enableDecryption: "false"
    decryptionKey:
    
proxyConfig:
    host:
    port:
    username:
    password:

# Global metrics config for all accounts
metricsConfig:

    # By default, all metrics retrieved from cloudwatch are 'Average' values.	
    # This option allows you to override the metric type. 
    #
    # metricName supports regex
    # Allowed statTypes are: ave, max, min, sum, samplecount
    #
    # Note: Irrespective of the metric type, value will still be reported as
    # Observed value to the Controller
    metricTypes:
      - metricName: ""
        statType: ""

    excludeMetrics: [ ]

    metricsTimeRange:
      startTimeInMinsBeforeNow: 5
      endTimeInMinsBeforeNow: 0

    # 
    # The max number of retry attempts for failed retryable requests 
    # (ex: 5xx error responses from a service) or throttling errors
    #
    maxErrorRetrySize: 0

concurrencyConfig:
  noOfAccountThreads: 3
  noOfRegionThreadsPerAccount: 3
  noOfMetricThreadsPerRegion: 3

#prefix used to show up metrics in AppDynamics 
metricPrefix: "Custom Metrics|Amazon Lambda|"